/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ox_group;


import javax.swing.ImageIcon;
/**
 *
 * @author Demon
 */
public class LoginPage extends javax.swing.JFrame {

    /**
     * Creates new form LoginPage
     */
    public LoginPage() {
        initComponents();
       
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        button_login = new javax.swing.JLabel();
        input_Username = new javax.swing.JTextField();
        input_Pass = new javax.swing.JPasswordField();
        button_signup = new javax.swing.JLabel();
        button_close = new javax.swing.JLabel();
        BG_Login = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(1024, 768));
        setMinimumSize(new java.awt.Dimension(1024, 768));
        setUndecorated(true);
        setResizable(false);
        getContentPane().setLayout(null);

        button_login.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imgs/bt-li2.png"))); // NOI18N
        button_login.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                button_loginMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                button_loginMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                button_loginMouseExited(evt);
            }
        });
        getContentPane().add(button_login);
        button_login.setBounds(640, 590, 250, 40);

        input_Username.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                input_UsernameFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                input_UsernameFocusLost(evt);
            }
        });
        getContentPane().add(input_Username);
        input_Username.setBounds(680, 396, 210, 30);

        input_Pass.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                input_PassFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                input_PassFocusLost(evt);
            }
        });
        getContentPane().add(input_Pass);
        input_Pass.setBounds(680, 438, 210, 30);

        button_signup.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imgs/bt-su.png"))); // NOI18N
        button_signup.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                button_signupMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                button_signupMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                button_signupMouseExited(evt);
            }
        });
        getContentPane().add(button_signup);
        button_signup.setBounds(640, 490, 250, 40);

        button_close.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imgs/bt-close.png"))); // NOI18N
        button_close.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                button_closeMouseClicked(evt);
            }
        });
        getContentPane().add(button_close);
        button_close.setBounds(980, 10, 30, 30);

        BG_Login.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imgs/BG_Login2.jpg"))); // NOI18N
        BG_Login.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        getContentPane().add(BG_Login);
        BG_Login.setBounds(0, 0, 1024, 768);

        jLabel1.setText("jLabel1");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(730, 590, 41, 16);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void button_signupMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_button_signupMouseClicked
       RegisterPage RP = new RegisterPage();
        RP.setVisible(true);
       this.dispose();
      
       

    }//GEN-LAST:event_button_signupMouseClicked

    private void input_UsernameFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_input_UsernameFocusGained

        input_Username.setText("");
    }//GEN-LAST:event_input_UsernameFocusGained

    private void input_UsernameFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_input_UsernameFocusLost
        if(input_Username.getText().equals("")){
            input_Username.setText("Username");
        }

    }//GEN-LAST:event_input_UsernameFocusLost

    private void input_PassFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_input_PassFocusGained
        input_Pass.setText("");
    }//GEN-LAST:event_input_PassFocusGained

    private void input_PassFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_input_PassFocusLost
        if(input_Pass.getText().equals("")){
            input_Pass.setText("Password");
        }

    }//GEN-LAST:event_input_PassFocusLost

    private void button_closeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_button_closeMouseClicked
        System.exit(0);
    }//GEN-LAST:event_button_closeMouseClicked

    private void button_signupMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_button_signupMouseEntered
          ImageIcon img = new ImageIcon(this.getClass().getResource("../imgs/bt-su2.png"));
          button_signup.setIcon(img);
    }//GEN-LAST:event_button_signupMouseEntered

    private void button_signupMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_button_signupMouseExited
         ImageIcon img = new ImageIcon(this.getClass().getResource("../imgs/bt-su.png"));
          button_signup.setIcon(img);
    }//GEN-LAST:event_button_signupMouseExited

    private void button_loginMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_button_loginMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_button_loginMouseClicked

    private void button_loginMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_button_loginMouseEntered
       ImageIcon img = new ImageIcon(this.getClass().getResource("../imgs/bt-li.png"));
          button_login.setIcon(img);
    }//GEN-LAST:event_button_loginMouseEntered

    private void button_loginMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_button_loginMouseExited
         ImageIcon img = new ImageIcon(this.getClass().getResource("../imgs/bt-li2.png"));
          button_login.setIcon(img);
    }//GEN-LAST:event_button_loginMouseExited

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(LoginPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(LoginPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(LoginPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(LoginPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new LoginPage().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel BG_Login;
    private javax.swing.JLabel button_close;
    private javax.swing.JLabel button_login;
    private javax.swing.JLabel button_signup;
    private javax.swing.JPasswordField input_Pass;
    private javax.swing.JTextField input_Username;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
